// <auto-generated />
namespace Maxtrain.Maximal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedcodetoroleandprivilege : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcodetoroleandprivilege));
        
        string IMigrationMetadata.Id
        {
            get { return "201812131921372_added code to role and privilege"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
